### ISSUE TITLE
zenity - can't control position/geometry (use yad instead)

### ISSUE THREAD

**Issue by 0Ky** [sebbekarlsson/i3-volume-ctrl#1]
Can you replace zenity to [yad](https://github.com/v1cont/yad), it's just superior to zenity since it has more controls and options. It's a fork of Zenity program.

**Comment by sebbekarlsson** [comment]
Create a pull request! 😺

**Comment by jmrr** [comment]
I've created #4 but just to contribute a personal preference, perhaps more people with more experience could chip in?

**Comment by sebbekarlsson** [comment]
I merged the solution from @jmrr  , I tested it and it looks good. Thank you!
